#!/bin/bash
Xvfb :99 -screen 0 1280x1024x24 &
export DISPLAY=:99
fluxbox &
x11vnc -display :99 -nopw -listen localhost -forever &
/opt/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 8080 &
/stable-retro/gym-retro-integration